import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { Employee } from '../types/Employee';


/**
 * Interface representing the state structure for the employees.
 * @typedef {Object} EmployeeState
 * @property {Employee[]} employees - Array of employees.
 */
export interface EmployeeState {
  employees: Employee[];
}

/**
 * The initial state for the employee slice.
 * @type {EmployeeState}
 */
const initialState: EmployeeState = {
  employees: [],
};

/**
 * `employeeSlice` is a Redux slice that manages the employee data in the application.
 * It provides actions to add a new employee and delete employees from the list.

 */
const employeeSlice = createSlice({
  name: 'employees',
  initialState,
  reducers: {
    /**
     * Adds a new employee to the state.
     * 
     * @param {EmployeeState} state - The current state of the employee slice.
     * @param {PayloadAction<Employee>} action - The action containing the employee to add.
     */
    addEmployee: (state, action: PayloadAction<Employee>) => {
      state.employees.push(action.payload);
    },
    /**
     * Deletes an employee from the state.
     * 
     * If the action payload is `-1`, all employees are removed from the state.
     * Otherwise, the employee at the specified index is removed.
     * 
     * @param {EmployeeState} state - The current state of the employee slice.
     * @param {PayloadAction<number>} action - The action containing the index of the employee to delete, or `-1` to clear all.
     */
    deleteEmployee: (state, action: PayloadAction<number>) => {
      if (action.payload === -1) {
        // Clear all employees
        state.employees = [];
      } else {
        state.employees = state.employees.filter((_, index) => index !== action.payload);
      }
    },
  },
});

/** 
 * Action creators generated from the `employeeSlice` reducers.
 * @type {{ addEmployee: (employee: Employee) => void, deleteEmployee: (index: number) => void }}
 */
export const { addEmployee, deleteEmployee } = employeeSlice.actions;

/**
 * The reducer generated by the `employeeSlice`, to be used in the Redux store.
 * 
 * @type {import('redux').Reducer<EmployeeState>}
 */
export default employeeSlice.reducer;
