import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { Employee } from '../types/Employee';


/**
 * Interface representing the state structure for the employees.
 * @typedef {Object} EmployeeState
 * @property {Employee[]} employees - Array of employees.
 */
export interface EmployeeState {
  employees: Employee[];
}

/**
 * The initial state for the employee slice.
 * @type {EmployeeState}
 */
const initialState: EmployeeState = {
  employees: [],
};

/**
 * `employeeSlice` manages the employee data within the application.
 * It includes reducers for adding and deleting employees.
 * 
 * @name employeeSlice
 */
const employeeSlice = createSlice({
  name: 'employees',
  initialState,
  reducers: {
    /**
     * Adds a new employee to the state.
     * 
     * @param {EmployeeState} state - The current state of the employee slice.
     * @param {PayloadAction<Employee>} action - The action containing the employee to add.
     */
    addEmployee: (state, action: PayloadAction<Employee>) => {
      state.employees.push(action.payload);
    },
    /**
     * Deletes an employee from the state.
     * 
     * If the action payload is `-1`, all employees are removed from the state.
     * Otherwise, the employee at the specified index is removed.
     * 
     * @param {EmployeeState} state - The current state of the employee slice.
     * @param {PayloadAction<number>} action - The action containing the index of the employee to delete, or `-1` to clear all.
     */
    deleteEmployee: (state, action: PayloadAction<number>) => {
      if (action.payload === -1) {
        // Remove all employees
        state.employees = [];
      } else {
        state.employees = state.employees.filter((_, index) => index !== action.payload);
      }
    },
  },
});

/**
 * Action creators generated from the `employeeSlice` reducers.
 * 
 * @type {Object}
 * @property {(employee: Employee) => void} addEmployee - Action creator to add an employee.
 * @property {(index: number) => void} deleteEmployee - Action creator to delete an employee by index or clear all.
 */
export const { addEmployee, deleteEmployee } = employeeSlice.actions;

/**
 * The reducer function generated by `employeeSlice` to be used in the Redux store.
 * 
 * @type {import('redux').Reducer<EmployeeState>}
 */
export default employeeSlice.reducer;
